version: '3'
services:
  postgres:
    container_name: sec_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: secdb
    ports:
      - '5432:5432'
    restart: always